Fix for #409
graphql-java-kickstart/graphql-java-tools pull request #414
Opened 2020-07-04 21:15 UTC by KammererTob

Fixes #409 

## Checklist
- [x] Pull requests follows the [contribution guide](https://github.com/graphql-java-kickstart/graphql-java-tools/wiki/Contribution-guide)
- [x] New or modified functionality is covered by tests

## Description
I tried to fix #409 with this PR. Quick rundown of the problem and what my attempt to fix it was:
This commit https://github.com/graphql-java-kickstart/graphql-java-tools/commit/10ee43f3e00f25194323a6ab7c1a9a4481726ca6 tried to address https://github.com/graphql-java-kickstart/graphql-java-tools/issues/385 by using `GraphQLInputObjectTypes` instead of just `GraphQLTypeReferences`. The `GraphQLInputObjectTypes` will be populated with a full list of field definitions, which in turn will create `GraphQLInputObjectTypes` if necessary. The stackoverflow occured when a field needed to create a `GraphQLInputObjectType`, which then would have a reference back to any ancestor in the creation chain. Since at that point the ancestor did not yet exist in the `inputObjects` list the function tries to create it again, which restarts the whole chain.

My fix: Instead of using `GraphQLInputObjectTypes` for everything we keep a list of all ancestors (called referencingInputObjects). If we then encounter a type which already is in this list we return a `GraphQLTypeReference`  instead of the full `GraphQLInputObjectType` again. This should hopefully allow https://github.com/graphql-java-kickstart/graphql-java-tools/issues/385 to still be functional, while also fixing #409, although i did **not** test, for that. So maybe someone more knowledgeable should have a look at this specific use-case.

2020-09-04 21:17 UTC, tedepstein commented
Any news on this pull request? I have also encountered this issue.

2020-09-29 20:30 UTC, edacostacambioupgrade approved these changes

2020-10-06 08:44 UTC, lnorregaard commented
I have also just run into this. Any knowledge of the fix for this

2020-11-17 22:02 UTC, vojtapol requested changes
Thank you for your contribution! Please address the conflict and we can merge this.

2020-12-14 21:43 UTC, vojtapol approved these changes

2020-12-14 21:43 UTC, merged