#434 Add GraphQlInputObjectType reference for NonNull INput types at …
graphql-java-kickstart/graphql-java-tools pull request #435
Opened 2020-09-16 19:21 UTC by elielsonms

Fixes #434  Add GraphQlInputObjectType reference for NonNull INput types at …Runtime Wiring

## Checklist

- [x] Pull requests follows the [contribution guide](https://github.com/graphql-java-kickstart/graphql-java-tools/wiki/Contribution-guide)
- [x] New or modified functionality is covered by tests

## Description
- Added to the determineType the same approach as  determineInputType, but without the creation of nonexisting INput types (this could lead to infinity recursion)
- Added Groovy Unit Test to ensure the problem is solved

2020-11-17 22:28 UTC, vojtapol requested changes
Could you please check how does this relate to this: https://github.com/graphql-java-kickstart/graphql-java-tools/pull/414 ?

2020-11-18 00:00 UTC, elielsonms commented
> Could you please check how does this relate to this: #414 ?

They seems to be similar, but I saw that issue before and looking by it's code I wondered it would not solve "my problem". But now I download that branch and ran my Unit test and it failed, so sadly they don't relate. As far as I rechecked in #414 code he's tackling an issue about cyclic reference, which can lead to stackoverflow. And my PR try to solve the problem of at runtime the library graphql-java-extended-validation (but any other "code" could fall into this issue too) is expecting an GraphQlInputObjectType but for Non Null types we just have the GraphQLTypeRefernce for the type that should not be null. This GraphQLTypeRefernce will only be replaced by "its imeplementation" of GraphQlInputObjectType at the end of the Schema parsing, so any DirectiveWiring, that executes in the middle of the Schema parsing, would not have access to the already created GraphQlInputObjectType

2020-12-15 21:21 UTC, oryan-block requested changes
This looks good to me. Just a couple minor suggestions.

2020-12-15 21:21 UTC, oryan-block commented on src/main/kotlin/graphql/kickstart/tools/SchemaParser.kt
> +                    val found = inputObjects.filter { it.name == typeDefinition.name }
This can be replaced with
`inputObjects.find { it.name == typeDefinition.name } ?: GraphQLTypeReference(typeDefinition.name)`

2020-12-15 21:21 UTC, oryan-block commented on src/test/groovy/graphql/kickstart/tools/SchemaParserSpec.groovy
> +                                    assert (environment.getElement().type as graphql.schema.GraphQLNonNull).wrappedType.class == GraphQLInputObjectType
No need for the fully qualified import of `GraphQLNonNull`

2020-12-15 21:21 UTC, oryan-block commented on src/test/groovy/graphql/kickstart/tools/SchemaParserSpec.groovy
> +        (testNonNullableArgument.type as graphql.schema.GraphQLNonNull).wrappedType.class == GraphQLInputObjectType
Here too `GraphQLNonNull`

2020-12-16 14:08 UTC, oryan-block approved these changes

2021-03-05 20:11 UTC, oryan-block submitted a review, later dismissed

2021-03-05 20:31 UTC, oryan-block approved these changes

2021-03-05 20:43 UTC, vojtapol approved these changes

2021-03-05 20:43 UTC, merged