Add an option to fallback to comments if a description is not provided
graphql-java-kickstart/graphql-java-tools pull request #459
Opened 2020-11-25 21:53 UTC by rideliner

## Checklist
- [x] Pull requests follows the [contribution guide](https://github.com/graphql-java-kickstart/graphql-java-tools/wiki/Contribution-guide)
- [x] New or modified functionality is covered by tests

## Description
The existing behavior is to always fallback to comments from the schema. This change would add a configuration option to `SchemaParserOptions` that would make it possible to ignore comments and exclusively use descriptions from the schema.

For example:
```graphql
# Copyright 2020
# Authors: ...

type Query {
    hello: String!
}
```
This schema with the current behavior would result in the description being `Copyright 2020\nAuthors: ...`.
With the `commentsAsFallbackDescription` option set as false, the description will be null.

2020-12-08 15:28 UTC, vojtapol requested changes

2020-12-08 15:28 UTC, vojtapol commented on src/main/kotlin/graphql/kickstart/tools/util/Utils.kt
> +        node.comments.isEmpty() -> null
you can use `isNullOrEmpty()` to combine the two previous lines

2020-12-08 15:28 UTC, vojtapol commented on src/main/kotlin/graphql/kickstart/tools/SchemaParserOptions.kt
> +    val commentsAsFallbackDescription: Boolean
let's rename this to `useCommentsForDescriptions`

2021-03-05 20:13 UTC, oryan-block commented
@rideliner please resolve to conflict. We've migrated all tests to kotlin so you can leave it out. I can recreate your test after that.

2021-04-23 22:32 UTC, florensie commented on src/main/kotlin/graphql/kickstart/tools/util/Utils.kt
> +        node.comments.isNullOrEmpty() -> null
These two conditions both return `null` so you could just combine them into one.

2021-05-18 14:47 UTC, oryan-block approved these changes
Looks good 🚀

2021-08-13 15:09 UTC, vojtapol approved these changes

2021-08-13 19:37 UTC, oryan-block commented
Closing this since we're unable to push/merge it as it is. Opened https://github.com/graphql-java-kickstart/graphql-java-tools/pull/564/ with the same commits.

2021-08-13 19:37 UTC, closed without merging