Upgrade kotlin to 1.4.10 and kotlin coroutines to 1.4.2
graphql-java-kickstart/graphql-java-tools pull request #473
Opened 2021-01-16 14:48 UTC by oliemansm

Fixes #451

## Checklist

- [x] Pull requests follows the [contribution guide](https://github.com/graphql-java-kickstart/graphql-java-tools/wiki/Contribution-guide)
- [x] New or modified functionality is covered by tests

## Description
Upgraded the versions in pom.xml properties and fixed one failing test.

2021-01-19 07:16 UTC, avolz requested changes

2021-01-19 07:16 UTC, avolz commented on pom.xml
> +        <kotlin.version>1.4.10</kotlin.version>
There is a newer version since December 7, 2020 available. Why you use 1.4.10?
```suggestion
        <kotlin.version>1.4.21</kotlin.version>
```

2021-01-19 07:20 UTC, avolz approved these changes

2021-02-16 20:55 UTC, oryan-block approved these changes

2021-02-16 21:54 UTC, merged