Prevent to add PageInfo definition if not needed
graphql-java-kickstart/graphql-java-tools pull request #476
Opened 2021-01-20 13:18 UTC by ooga

## Checklist

- [x] Pull requests follows the [contribution guide](https://github.com/graphql-java-kickstart/graphql-java-tools/wiki/Contribution-guide)
- [x] New or modified functionality is covered by tests

## Description

Prevent `RelayConnectionFactory` to do extra work and add new definition when not needed.

2021-02-16 21:11 UTC, oryan-block commented
Can you provide an example schema where this is a problem?
I'm not sure I understand what we're trying  to solve here.

2021-02-26 15:06 UTC, vojtapol commented
I believe the problem is that we are always adding some baked-in types to facilitate the relay `@connection` directive. If the users want to have their own type called `PageInfo` for whatever reason they can't because it clashes.

2021-02-26 15:11 UTC, vojtapol requested changes
Thanks for the contribution!

2021-02-26 15:11 UTC, vojtapol commented on src/test/kotlin/graphql/kickstart/tools/relay/RelayConnectionFactoryTest.kt
> +        Assert.assertEquals(newDefinitions.size, 0)
Please static-import `assertEquals`.

2021-02-26 15:11 UTC, vojtapol commented on src/main/kotlin/graphql/kickstart/tools/relay/RelayConnectionFactory.kt
> +        if (connectionDirectives.isEmpty()) {
```suggestion
        if (connectionDirectives.isEmpty()) {
            // do not add Relay definitions unless needed
```

2021-03-04 19:10 UTC, oryan-block approved these changes

2021-03-04 19:11 UTC, vojtapol approved these changes

2021-03-04 19:11 UTC, merged