Test case and should fix for #558
graphql-java-kickstart/graphql-java-tools pull request #559
Opened 2021-07-30 13:17 UTC by marcus-nl

Fixes #588

## Checklist

- [x] Pull requests follows the [contribution guide](https://github.com/graphql-java-kickstart/graphql-java-tools/wiki/Contribution-guide)
- [x] New or modified functionality is covered by tests

## Description
DictionaryTypeResolver now considers the full type hierarchy -- superinterfaces in addition to superclasses.

2021-08-04 14:32 UTC, oryan-block requested changes
Thanks for the fix. I have one request.

2021-08-04 14:32 UTC, oryan-block commented on src/test/kotlin/graphql/kickstart/tools/EndToEndSpecHelper.kt
> +class OutOfBeerError(val msg: String)
Can we think of a better example hierarchy here? Maybe `animal -> pet -> dog`?

2021-08-04 14:34 UTC, oryan-block commented on src/test/kotlin/graphql/kickstart/tools/EndToEndSpecHelper.kt
> +        return listOf(BarEntityImpl("123", "Bar Name"))
This method can be converted to an expression body.

2021-08-05 08:49 UTC, marcus-nl commented
Updated. 
(I could not use `animal -> pet -> dog`, since Animal was already defined in the same package in TestInterfaces.kt)

2021-08-05 16:27 UTC, oryan-block approved these changes

2021-08-05 16:27 UTC, merged