Scan for resolvers that have a supertype of the data class
graphql-java-kickstart/graphql-java-tools pull request #638
Opened 2022-02-22 19:28 UTC by florensie

Fixes #497

## Checklist
- [x] Pull requests follows the [contribution guide](https://github.com/graphql-java-kickstart/graphql-java-tools/wiki/Contribution-guide)
- [x] New or modified functionality is covered by tests

## Description
Made necessary changes to class scanning logic to support using supertypes in resolvers.

2022-03-11 14:41 UTC, oryan-block requested changes
Thanks for the contribution 👍 
I have some questions.

2022-03-11 14:41 UTC, oryan-block commented on src/main/kotlin/graphql/kickstart/tools/SchemaClassScanner.kt
> +                    MultiResolverInfo(resolverInfoList, item.clazz.unwrap())
Why multi if there's only one?

2022-03-11 14:41 UTC, oryan-block commented on src/main/kotlin/graphql/kickstart/tools/resolver/FieldResolverScanner.kt
> +                it == search.requiredFirstParameterType || (it is Class<*> && it.unwrap().isAssignableFrom(search.requiredFirstParameterType))
Do we need the cast to Class here?

2022-06-15 07:22 UTC, closed without merging

2023-05-25 08:37 UTC, swollner commented
Hi is there any progress on this?

2023-05-28 17:36 UTC, florensie commented
@swollner None beyond this PR. Best to keep discussion to #497, feel free to use this PR as a reference/base if you wish to contribute yourself.